name: CI & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Nettoyage du cache pour forcer une reconstruction complète
      - name: Clean cache
        run: npm cache clean --force
        
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check docs contents
        run: |
          ls -la docs
          ls -la docs/assets
          echo "Vérification du contenu des fichiers JS"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
